- taigit/package-lock.json
- taigit/package.json
- taigit/src/libraries/Taiga.ts
- taigit/src/react-app-env.d.ts
- taigit/tsconfig.json
- taigit/yarn.lock
It's not much but the point was to add a taiga library into the project, not to integrate taiga functionality
I actually did test this by adding some basic login functionality to the Taiga Component: 
```
import React, { Component } from 'react';
import {taiga_login}  from '../libraries/Taiga'
export default class Taiga extends Component {
constructor(props) {
super(props);
this.state = {
username: '',
password: ''
};
this.on_change = this.on_change.bind(this);
this.on_submit = this.on_submit.bind(this);
}
on_change(event) {
this.setState({
[event.target.name]: event.target.value
});
}
on_submit(event) {
taiga_login(this.state.username, this.state.password).then((ret)=>{
if(ret) alert("taiga login: successful");
else    alert("taiga login: unsuccessful");
});
event.preventDefault();
} …
```
> US18T32 Introduce Base Taiga Architecture

- taigit/src/components/Taiga.js
- taigit/src/components/charts/StackedBarChart.js
- taigit/src/components/charts/stackedBarChartData.js
- taigit/src/styles/App.scss
Created a mock component for displaying tasks completed and in progress per team member.
> US-12 Taiga Tasks Per Person Component

- taigit/src/components/Taiga.js
- taigit/src/components/charts/DoughnutChart.js
- taigit/src/styles/App.scss
Added a User Story Progress Component for the Taiga Page
To Test:
> US-12 Task-58 User Story Progress Component

- taigit/package-lock.json
- taigit/src/components/Overview.js
- taigit/src/components/charts/LineChart.js
Added graph with github contributions for just 2 users can be increased later with the number of users as we have the data coming in from the API
> US#10 Task#52 Github commits contribution graph to show on Overview tab

- taigit/package-lock.json
- taigit/src/components/Overview.js
- taigit/src/components/Taiga.js
- taigit/src/components/charts/DoughnutChart.js
- taigit/src/components/charts/LineChart.js
Checkout the code. Tried solving errors and it's working now
> US #14 Task #50, #51Solved errors and tried adding mock data for the overview page

- taigit/src/components/GitHub.js
- taigit/src/components/charts/BarChart.js
- taigit/src/components/charts/barChartData.js
- taigit/src/styles/App.scss
Added three components for the GitHub page: Number of pull requests created, Number of pull requests reviewed, Number of commits by team member.
To Test:
> Us 12 GitHub components

- taigit/src/libraries/Taiga.ts
To test add this line (and import project_info) to any one of the front end .js files in the project and view the output in the console window
```
{console.log(project_info('halcyonaura-quiz-creator').then((val)=> 
{console.log('fe', val)}
))}
```
You should get the following values:
`{id: 309976, name: "Quiz Creator", slug: "halcyonaura-quiz-creator", created_date: "2019-02-15T01:07:23.636Z"}`
> Us20 t77 project info

- taigit/src/libraries/Taiga.ts
Reverts ser574-green-team/taigit#20
> Revert "Us20 t77 project info"

- taigit/src/libraries/Taiga.ts
undo the revert to re-open the PR @HalcyonAura
> Revert "Revert "Us20 t77 project info""

- taigit/src/libraries/Taiga.ts
Similar testing as before, import project_stats from Taiga.ts library then add the following to a react component of your choosing
`{console.log(project_stats(309976).then((val) =>
{console.log('fe', val)}
))}`
To validate make sure the console outputs:
`fe {name: "Quiz Creator", total_milestones: null, total_points: null, closed_points: 0, closed_points_per_role: {…}, …}`
> Adding call for project stats

- taigit/package-lock.json
- taigit/package.json
- taigit/src/actions/githubActions.js
- taigit/src/actions/taigaActions.js
- taigit/src/components/GitHub.js
- taigit/src/components/MemberProfile.js
- taigit/src/components/Taiga.js
- taigit/src/components/Team.js
- taigit/src/index.js
- taigit/src/reducers/githubReducer.js
- taigit/src/reducers/index.js
- taigit/src/reducers/taigaReducer.js
- taigit/src/reducers/team.js
- taigit/src/reducers/teamReducer.js
- taigit/src/store.js
This creates the basic redux store structure for the project.
This branch connects team member info, and some small GitHub and Taiga data to the redux store.
- _src/actions_ contains all actions on the store that the UI will call (GitHub has one that utilizes a GitHub api call)
- _src/reducers_ contains code that gets run when an action is called, and grabs data from the result of the action to update the store
_Note: you'll need to run `npm install` before testing as I've added two new dependencies_
> Redux structure

- taigit/src/libraries/Taiga.ts
resolve conflict with dev for US102Task113,117,118
Us102 task113 API call to return user stats and user story total points
Test instructions:
1 userstory_total_points
To test add this line (and import userstory_points) to any one of the front end .js files in the project and view the output in the console window
Test add-on:
import {userstory_total_points} from '../libraries/Taiga'
{console.log(userstory_total_points(2698838).then((val) => {console.log('fe', val)} ))}
Expected Result:
fe {total_points: 3}total_points: 3__proto__: Object
2 user_stats API call returns task stats based on task Id
To test add this line (and import user_stats) to any one of the front end .js files in the project and view the output in the console window
Test add-on:
import {user_stats} from …
> resolve conflict with dev for US102Task113,117,118

- taigit/src/libraries/Taiga.ts
Reverts ser574-green-team/taigit#43
This is to handle david's bad merge request. It will be remerged once things are fixed.
> Revert "US137-Task147: Get all the user story titles for analysis"

- taigit/src/libraries/Taiga.ts
Reverts ser574-green-team/taigit#35
This is to handle david's bad merge request. It will be remerged once things are fixed.
> Revert "US102-task114: Get the list of user's in a project"

- taigit/src/libraries/Taiga.ts
This resolves the earlier repo problems and does not need to be reviewed as it has been taken from the latest possible commit before the merge to dev.
> Us102 task114 fix

- taigit/src/actions/githubActions.js
- taigit/src/components/GitHub.js
- taigit/src/libraries/GitHub/GitHub.js
- taigit/src/libraries/GitHub/src/contributorData.ts
- taigit/src/reducers/githubReducer.js
- taigit/src/reducers/index.js
To Test:
Start up the app and make sure the graph in the image below appears.
> Connects Commits Per Member to Redux Store

- taigit/package-lock.json
- taigit/package.json
- taigit/src/components/Taiga.js
- taigit/src/reducers/index.js
- taigit/src/reducers/taigaReducer.js
- taigit/src/styles/App.scss
Adds a dropdown which selects which sprint data to view on taiga.
_Note: Waiting on backend calls to be created, to get full sprint data_
> Sprint Selection Dropdown

- taigit/src/actions/githubActions.js
- taigit/src/components/GitHub.js
- taigit/src/components/ScrollableList.js
- taigit/src/reducers/githubReducer.js
- taigit/src/styles/App.scss
To Test:
Open app and make sure that after any resizing, the component is displayed like so:
> Styling Branch List Component

- taigit/src/libraries/Taiga.ts
to test it should be fairly simple:
sprint_list(projectID) 
userstory_list(sprintID) 
task_list(userstoryID)
> T186 get list of sprints, userstories, and tasks

- taigit/src/libraries/Taiga.ts
This call return a task used time based on task Id.
There are  timecost will be returned.
*               timecost: number,  //time of history entry cost in milliseconds
*               acctime: number,   //time of task accumulated of this history entry cost in milliseconds
To Test add following code in Taiga.js:
import {task_assessment_time}  from '../libraries/Taiga'
{console.log(task_assessment_time(2577741).then((val) => {console.log('fe', val)} ))}
Expected Result:
fe (3) [{…}, {…}, {…}] 0: {date: 1541629794485, timecost_m: 0, acctime_m: 0, timecost_h: 0, acctime_h: 0, …} 1: acctime_h: 211.73466694444443 acctime_m: 762244801 date: 1542392039286 status_trans: (2) ["In progress", "Ready for test"] timecost_h: 211.73466694444443 timecost_m: 762244801 __proto__: Object 2: {date: …
> US139 Task155 API to return task used time

- taigit/src/components/MemberProfile.js
- taigit/src/components/Team.js
- taigit/src/reducers/githubReducer.js
- taigit/src/reducers/index.js
- taigit/src/reducers/teamReducer.js
- taigit/src/styles/App.scss
- taigit/src/styles/Team.scss
As side effect, totalCommits of a team member is connected on individual page
> [US-203 Task: 217-218]: Connected team list to team members page

- taigit/src/actions/githubActions.js
- taigit/src/components/GitHub.js
- taigit/src/libraries/GitHub/GitHub.js
- taigit/src/libraries/GitHub/src/auth.ts
- taigit/src/libraries/GitHub/src/getHistoryOfPR.ts
- taigit/src/libraries/GitHub/src/getMemberInfo.ts
Funciton to get username and avatar_id of ALL members in an organization.
> Us#111 task#134 - Get Org Members and History of PR

- taigit/package-lock.json
- taigit/src/actions/githubActions.js
- taigit/src/components/GitHub.js
- taigit/src/reducers/githubReducer.js
- taigit/src/reducers/index.js
Added component on UI to show the average number of comments on the Pull Requests.
> US#203 Task#267 Component on UI to show average number of comments on PR

- taigit/src/libraries/Taiga.ts
To test:
```
(async function(slug) {
let {id} = await taiga.project_info(slug);
let out = await taiga.id_to_roles(id);
console.log(out);
})("sanaydevi-ser-574");
```
You will get a list of objects that looks like this
(6) [{…}, {…}, {…}, {…}, {…}, {…}]
0: {role_id: 1868247, role_name: "UX"}
1: {role_id: 1868248, role_name: "Design"}
2: {role_id: 1868249, role_name: "Front"}
3: {role_id: 1868250, role_name: "Back"}
4: {role_id: 1868251, role_name: "Product Owner"}
5: {role_id: 1868252, role_name: "Stakeholder"}
> Us188 t235 convert

- taigit/src/libraries/Taiga.ts
To test:
```
(async function(slug) {
let {id} = await taiga.project_info(slug);
let out = await taiga.id_to_points(id);
console.log(out);
})("sanaydevi-ser-574");
```
To see:
```
{'3691426':  null,
'3691427': 0,
'3691428': 0.5,
'3691429': 1,
'3691430': 2,
'3691431': 3,
'3691432': 5,
'3691433': 8,
'3691434': 10,
'3691435': 13,
'3691436': 20,
'3691437': 40}
```
> Us188 t236 convert points

- taigit/src/actions/githubActions.js
- taigit/src/components/GitHub.js
- taigit/src/reducers/githubReducer.js
- taigit/src/reducers/index.js
to test: Visit the github page and verify that the builds are listed in a component (may take a couple seconds for the items to appear.)
> Us206 t266 display builds

- taigit/src/libraries/GitHub/GitHub.js
- taigit/src/libraries/GitHub/src/bytesOfCode.ts
Returns object with number of bytes of code of each programming language in the repo.
> Us 111 task 131 get bytes

- taigit/src/actions/githubActions.js
- taigit/src/components/GitHub.js
- taigit/src/reducers/githubReducer.js
- taigit/src/reducers/index.js
There is now a component which shows bytes on the github page.
> Us203 t283 bytes

- taigit/src/components/GitHub.js
Changed components for Code Quality Metrics with hard-coded data to Number Display as requested.
> Us#203 task#212

- taigit/src/components/GitHub.js
- taigit/src/libraries/GitHub/GitHub.js
- taigit/src/libraries/GitHub/src/getHistoryOfPR.ts
- taigit/src/libraries/GitHub/src/getMemberInfo.ts
Fucntion to getHistoryOfPull Requests.
Currently it returns the timestamp of Created_at, Closed_at and Merged_at. 
@FrontEnd let me know what else would you like in it and if you'll can incorporate it into front end.
@Github check if code is write.
> Us#193 task#264

- taigit/src/actions/githubActions.js
- taigit/src/components/GitHub.js
- taigit/src/reducers/githubReducer.js
- taigit/src/reducers/index.js
- taigit/src/utils/utils.js
To test,
1. Open a codacy account
2. add a repo you have admin access to to your codacy account
3. Open it in Taigit
4. Visit the github page.
> Adis components

- taigit/src/actions/githubActions.js
- taigit/src/components/GitHub.js
- taigit/src/reducers/githubReducer.js
To test: load up taigit, and look at the PR components. make sure they're accurate.
> PR components now display correctly.

- taigit/src/libraries/GitHub/src/commits.ts
This is literally the easiest PR. Please review it :)
> Made the date slightly easier to read

- taigit/src/components/Overview.js
- taigit/src/reducers/githubReducer.js
- taigit/src/reducers/index.js
Connected component with bytes of code data already in the store.
Example:
> Connected Overview Technologies Component
